Update diabetes_regression-ci.yml for Azure Pipelines

diff --git a/.pipelines/diabetes_regression-ci.yml b/.pipelines/diabetes_regression-ci.yml
--- a/.pipelines/diabetes_regression-ci.yml
+++ b/.pipelines/diabetes_regression-ci.yml
@@ -59,17 +59,17 @@ stages:
     container: mlops
     timeoutInMinutes: 0
     steps:
-  -task: AzureCLI@2
-  inputs:
-    azureSubscription: 'aml-workspace-connection'
-    scriptType: 'ps'
-    scriptLocation: 'inlineScript'
-    inlineScript: |
-      set -e # fail on error
-      export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
-      python -m ml_service.pipelines.run_train_pipeline --output_pipeline_id_file "pipeline_id.txt" --skip_train_execution
-      # Set AMLPIPELINEID variable for next AML Pipeline task in next job
-      AMLPIPELINEID="$(cat pipeline_id.txt)"
-      echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$AMLPIPELINEID"
+    -task: AzureCLI@2
+      inputs:
+        azureSubscription: 'aml-workspace-connection'
+        scriptType: 'ps'
+        scriptLocation: 'inlineScript'
+        inlineScript: |
+          set -e # fail on error
+          export SUBSCRIPTION_ID=$(az account show --query id -o tsv)
+          python -m ml_service.pipelines.run_train_pipeline --output_pipeline_id_file "pipeline_id.txt" --skip_train_execution
+          # Set AMLPIPELINEID variable for next AML Pipeline task in next job
+          AMLPIPELINEID="$(cat pipeline_id.txt)"
+          echo "##vso[task.setvariable variable=AMLPIPELINEID;isOutput=true]$AMLPIPELINEID"
  
  
